#!/bin/sh
lock() {
	file1=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
	file2=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)

	scrot -d0 "$file1"
	convert "$file1" -background black -scale 1%x10% -scale 10000%x1000% -level 12%\! -brightness-contrast -20x0 "$file2"
        i3lock -c 000000 -i "$file2"
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
