hooks:
  # hooks are executed in user's shell
  # available environment variables:
  #   randr_profile - name of the profile
  #   randr_error - error message if happens
  prior_switch: /usr/bin/killall -SIGSTOP i3
  post_switch: /usr/bin/killall -SIGCONT i3 && sleep 1 && wal -i "/home/jim/Pictures/wallpapers/profile/$randr_profile.jpg" && /usr/bin/notify-send -u low "randrctl" "switched to $randr_profile"
  post_fail: /usr/bin/killall -SIGCONT i3 && /usr/bin/notify-send -u critical "randrctl error" "can't switch to $randr_profile\n$randr_error"
